Add migration and seed for user roles with script to run both
Jpgomes06/subway-routes pull request #2
Opened 2024-09-10 00:40 UTC by Jpgomes06

2024-09-10 00:55 UTC, Luiz-Cruz requested changes

2024-09-10 00:55 UTC, Luiz-Cruz commented on prisma/migrations/20240904204742_init/migration.sql
> +
tem como a migration ser gerada com o nome da pasta envolvendo o contexto dela?
![alt text](image.png)

esse nome não diz muito sobre ela, creio que seja pelo script no terminal que você consiga mudar o nome, o ideal era ter o nome create-roles-table o algo do tipo.

2024-09-10 00:55 UTC, Luiz-Cruz commented on prisma/seed/.snaplet/dataModel.json
> +{
creio que esse arquivo não é necessário

2024-09-10 00:55 UTC, Luiz-Cruz commented on .env
> +DATABASE_URL=postgresql://postgres:dev123@localhost:5432/subway-db?schema=public
esse arquivo não deveria ser adicionado no seu repositório, crie um .gitignore e adicione o .env citado nele, como é um arquivo que contém dados sensíveis a gente não sobe ele no repositório.

2024-09-11 03:52 UTC, Luiz-Cruz requested changes

2024-09-11 03:52 UTC, Luiz-Cruz commented on .gitignore
> +.GITIGNORE
.gitignore
/node_modules

2024-09-11 03:52 UTC, Luiz-Cruz commented on prisma/migrations/20240910012357_create_roles_table/migration.sql
> +    "createAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
ficou errado createAt -> createdAt

2024-09-11 03:53 UTC, Luiz-Cruz commented on prisma/seed/seed.config.ts
> +import { SeedPrisma } from "@snaplet/seed/adapter-prisma";
checa no repo referência, mas é quase ctz que não precisa dele

2024-09-11 14:37 UTC, Luiz-Cruz requested changes

2024-09-11 14:37 UTC, Luiz-Cruz commented on .gitignore
> +.gitignore
deletar, você está mencionando o próprio .gitignore dentro dele próprio.

2024-09-11 16:26 UTC, Luiz-Cruz commented on prisma/seed/roles.ts
> +
add uma linha separando os imports do const

2024-09-11 16:27 UTC, Luiz-Cruz commented on prisma/seed.ts
> +        process.exit(1)
o que faz esse process.exit(1)?

2024-09-19 00:15 UTC, Jpgomes06 commented on prisma/seed.ts
> +        process.exit(1)
O process.exit com numero zero indica que o processo foi concluido com sucesso e qualquer outro numero indica um erro, no caso foi o numero um

2024-09-23 16:03 UTC, merged